Env: "dev"

DatabaseSettings:
  DatabaseURI: "root:eHtSbaMfKMhrrCBjzjE5@tcp(containers-us-west-151.railway.app:7839)/railway?parseTime=True&loc=Local"
  DatabaseName: "railway"
  Username: "root"
  Password: "eHtSbaMfKMhrrCBjzjE5"


JwtSettings:
  SecretKey: "KH-Liu"